version: '3'
services:
  app:
    build: .
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - TZ=Asia/Seoul
    ports:
      - "80:8080"
    depends_on:
      - db
      - redis
  db:
    image: postgres:9.6.1
    volumes:
      - ./config/app/init-db/postgres:/docker-entrypoint-initdb.d/
      - db-data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=assignment
      - POSTGRES_USER=chb
      - POSTGRES_PASSWORD=chb
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
      - TZ=Asia/Seoul
    ports:
      - "5432:5432"
  redis:
    image: redis
    volumes:
      - ./data:/var/lib/redis/data
    ports:
      - "6379:6379"
volumes:
  db-data: